hyperledger/fabric-protos

peer/proposal.proto
peer/proposal_response.proto

This field is only ever referenced in the endorserment proposal
validation (not in commit validation) and is of no use and only adds
confusion.  Removing.
Change-Id: Icd7b7d1a70310d8d41cea43d52d4365c996ce861
Signed-off-by: Jason Yellick <jyellick@us.ibm.com>

FAB-16353 Remove PayloadVisbility field

---

peer/chaincode_shim.proto

Chaincode service definition that allows a Peer to "Connect" as q client.
Currently supports only streams but eventually can be extended to support
unary Invoke calls.
Signed-off-by: muralisr <srinivasan.muralidharan99@gmail.com>

[FAB-14156] create chaincode server

---

peer/transaction.proto

This message appears to have been created, but isn't actually consumed
anywhere in the Fabric codebase:
$ cd fabric && pt -c SignedTransaction
./vendor/github.com/hyperledger/fabric-protos-go/peer/transaction.pb.go:19
Signed-off-by: Jason Yellick <jyellick@us.ibm.com>

Remove unused proto

---

common/common.proto

The last config index is now included in the SIGNATURES
metadata field.
Signed-off-by: Will Lahti <wtlahti@us.ibm.com>

FAB-15817 Deprecate LAST_CONFIG metadata field

---

peer/configuration.proto

* PrivateDataImplicitCollectionConfig stores the configuration for
org-specific implicit collections

[FAB-17303] Support new organization configuration field in channel config

---

discovery/protocol.proto

Currently, when a client queries discovery with an endorsement query which has collections in the query, discovery intersects the available peers with the collection definition by removing peers which are not part of the collection since they do not have the pre-images required to read from the namespace.
However, the introduction of GetPrivateDataHash makes new use cases possible, namely scenarios where some of the endorsers of a transaction aren't in the collection, but they are fed with the pre-image via other means (e.g the transient field) and after validating the pre-image using GetPrivateDataHash, they can perform the same computation as peers that are in the collection. In such a case, discovery will filter out those peers needlessly.
Furthermore, we want to be able to support …

Extend discovery protos for FAB-17308

---

gossip/message.proto

Part of FAB-17672:
Gossip bootstrap peer and anchor peer connection establishments are a two step process:
I)  Connect to the remote endpoint, and figure out its organization association
II) Connect to the remote endpoint once again, this time sending membership information according to what it is eligible to.
Unfortunately, if the responding peer connects to the initiator peer at the same time, the connection of (1) will be overwritten by the connection (gossip keeps a single connection among every pair of peers) from the responder peer and the initiator peer will consider the responder peer as dead.
In production, where peers run for a long time and constnatly retry, this is not a problem.
However, in integration tests that expect data to be disseminated in a timely manner, this might …

[FAB-17674] Add Probe flag to ConnEstablish

---

ci/Dockerfile
ci/azure-pipelines.yml

go-1.14.1
prototool-1.9.0
The protoc dependency was not updated as it requires a newer version of grpc-go that may impact existing clients.

Update go and prototool versions for CI

---

peer/lifecycle/lifecycle.proto

This patch extends lifecycle protos to add a function for querying the details of the approved chaincode definition.
Signed-off-by: Tatsuya Sato <Tatsuya.Sato@hal.hitachi.com>
- New feature
Currently, Fabric peer does not provide a function to query the details of approved chaincode definitions.
On the other hand, Fabric admins will need to confirm/use the information after approval for their operations.
So, we propose to add a function for querying the details of the approved chaincode definition to Fabric peer CLI (Refer to https://jira.hyperledger.org/browse/FAB-17401).
As a sub-task of FAB-17401, this patch extends lifecycle protos to add a function for querying the details of the approved chaincode definition.
Immediately after this patch has been merged into the fabric repository, …

[FAB-17432] Extend lifecycle protos to query the approved chaincode

---

common/common.proto

The peer admin service was removed.

Remove PEER_ADMIN_OPERATION type from protos

---

peer/snapshot.proto

Update snapshot.proto to include client_identity and rename `height` to `block_number`

[FAB-18117] Add client_identity and rename height to block_number in snapshot.proto

---

orderer/ab.proto

This option is added to allow a client listens to the future blocks only,
comparing to the existing Newest option which refers to the last block
that has been committed on the ledgerr.

[FAB-18235] Add NextAvailable seek position to ab.proto

---

common/ledger.proto

ledger.proto has mixed use of camelcase and underscore styles. It causes
inconsistence when marshalling to a string. Since the existing fields are
in camelcase, change new fields to camelcases as well.

Use camelcase consistently in ledger.proto

---

gateway/gateway.proto

The proto definition required by the gateway component. 
Moving from fabric-gateway repo to core fabric-protos to support embedding of gateway into peer

FABGW-1 Add proto definition for gateway

---

gateway/gateway.proto

The functions exposed by the gateway service make grpc client requests to external peers and orderers.  If any of these requests return an error, then these errors including the address of the remote endpoint are added to the Details field of the error returned by the gateway service.
This commit adds the message definition to the proto file to enable this capability.

Add error details to gateway proto

---

gateway/gateway.proto

- Now uses specific messages for requests and responses
- No streaming
- New rpc call to check the commit status of a transaction
- Use Response message from peer/proposal_response.proto so that
gateway clients can access result status and message as well as the
payload

Gateway updates

---

gateway/gateway.proto

- Include calling identity in CommitStatusRequest
- SignedCommitStatusRequest wraps a serialized CommitStatusRequest and digital signature
- CommitStatus service received a SignedCommitStatusRequest instead of CommitStatusRequest
Allows the server to:
- Ensure the request message was created by the expected client identity by verifying the signature
- Check that the calling identity has read permission for the channel

FABGW-19: Secure Gateway CommitStatus service

---

gateway/gateway.proto

Add support in the EndorseRequest message of the gateway proto for specifying which org’s peers to target.

FABGW-20 Specify endorsing organizations

---

gateway/gateway.proto

This service supports chaincode event listening in the client API.

FABGW-21: Add Gateway ChaincodeEvents service

---

gateway/gateway.proto

Add ‘endorsing_organizations’ fields to the gateway protobuf definitions for the Evaluate() method and for supporting offline
signing

FABGW-20 Protobuf for Evaluate() endorsingOrgs

---

discovery/protocol.proto
peer/proposal_response.proto

Add protobuf support for returning the derived chaincode interest structure from Tx simulation (process proposal).
Add the set of SBE signature policies to the discovery ChaincodeCall proto message
Add the ChaincodeInterest structure to the ProposalResponse message

FABGW-25 Extend proto to include derived interest

---

peer/proposal_response.proto

This commit adds a hint in the chaincode call of the discovery protobuf API
to signal that the client expects the namespace endorsement policy to be irrelevant.
Signed-off-by: Yacov Manevich <yacovm@il.ibm.com>

[FAB-18527] Hint to discovery to disregard the namespace endorsement policy

---

ci/Dockerfile

Update Go to 1.16.7.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>

Update Go to 1.16.7

---

gateway/gateway.proto

Default protoc binding is to a JavaScript number, which can only hold integers up to 2^53 - 1.

Bind uint64 fields to JavaScript strings in gateway.proto

---

gateway/gateway.proto

This reverts commit e08a20156346c7c6aaf97d4effa517689769367c.
Ensure consistently unhelpful (`number`) rather than inconsistently more helpful (`string`) default binding for uint64 fields in  JavaScript protobuf implementation classes generated by protoc. See #64.

Revert "Bind uint64 fields to JavaScript strings in gateway.proto (#63)"

---

gateway/gateway.proto

This name gets surfaced in the SDKs,  not as an error itself, but as extra information within an error/exception.  The name, ending in Error, is misleading in Java and Node.  This commit changes it to more appropriate name.
contributes to https://github.com/hyperledger/fabric/issues/2971

Change EndpointError to ErrorDetail

---

gateway/gateway.proto

This duplicates information already present in the EndorseResponse.prepared_transaction field and, if the content is large, can cause failures due to gRPC message size limits. The Fabric Gateway client and server implementations no longer use this field.
Contributes to hyperledger/fabric-gateway#316

Remove EndorseResponse.result field

---

ledger/rwset/kvrwset/kv_rwset.proto

This PR adds a field to capture the is_purge operation for enabling the purge of private data.
[Issue on fabric repo](https://github.com/hyperledger/fabric/issues/3021)
Signed-off-by: manish <manish.sethi@gmail.com>

Add `is_purge` field to KVWriteHash

---

gateway/gateway.proto

Add a `after_transaction_id` field to the ChaincodeEventsRequest message so the client can specify a transaction ID, up to which chaincode events should be ignored and not returned to the client.

Allow ChaincodeEvents to resume after a specific transaction ID

---

buf.yaml
orderer/blockattestation.proto

New block attestation service for BFT block replication and verification feature. 
Issue: https://github.com/hyperledger/fabric/issues/3413
Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>

New service and messages for block attestation

---

.github/workflows/gh-pages.yml

Previous attempt failed with…
ssh: Could not resolve hostname publish-pages: Temporary failure in name resolution

Publish generated API documentation

---

.github/workflows/go-bindings.yml

Build failed to find the script due to working-directory being publish-apiv2

Fix path to installDeployKey.sh script

---

.github/scripts/installDeployKey.sh

The key works locally but fails in the build for some reason…
```
Load key "/home/runner/.ssh/fabric-protos-go-apiv2_deploy_key": invalid format
```
Try using a base64 encoded key instead

Use base64 encoded deploy key

---

.github/workflows/java-bindings.yml

Signed-off-by: Ry Jones <ry@linux.com>

Allow Maven after Github fails

---

.github/workflows/ci-checks.yml
.github/workflows/java-bindings.yml
.github/workflows/node-bindings.yml

It would be useful to rerun the release build using the workflow_dispatch event, however this does not currently work because the workflows are checking the github ref for a v* version tag.
It’s not safe to always publish for a manual build and all the language bindings at a particular version should be published from the same commit, so this PR adds a job to the ci-checks workflow to look for the required version tag on the commit being built.

Allow release builds to be re-run manually

---

.github/workflows/node-bindings.yml

The node module should only be tagged with “latest” for released versions, and “unstable” otherwise

Only tag release versions as latest

---

.github/workflows/go-bindings.yml

Add version tags to the fabric-protos-go-apiv2 repository to match tagged releases in fabric-protos

Tag fabric-protos-go-apiv2 repo on release builds

---

docs/index.md

APIv2 is the preferred published binding for end user use.

Link to fabric-protos-go-apiv2 in docs

---

Makefile
common/common.proto

And turning the lint check back on.

Add identifier to MetadataSignature

---

orderer/clusterserver.proto

Proto definition for new orderer cluster service as described here: [RFC-ordererv3](https://github.com/hyperledger/fabric-rfcs/blob/main/text/orderer-v3.md#orderer-to-orderer-authentication-and-communication)
Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>

New orderer cluster service with auth support

---

bindings/java/pom.xml

Also update Java gRPC dependency to stay in step with protobuf-java.

Update protobuf-java dependency to address CVE-2022-3171

---

docs/Gemfile.lock

Signed-off-by: mik-patient <112659896+mik-patient@users.noreply.github.com>
With the Ruby data source (the tzinfo-data gem for tzinfo version 1.0.0 and later and built-in to earlier versions), time zones are defined in Ruby files. There is one file per time zone. Time zone files are loaded with require on demand. In the affected versions, `TZInfo::Timezone.get` fails to validate time zone identifiers correctly, allowing a new line character within the identifier. With Ruby version 1.9.3 and later, `TZInfo::Timezone.get` can be made to load unintended files with require, executing them within the Ruby process.
```rb
TZInfo::Timezone.get("foo\n/../../../../../../../../../../../../../../../../tmp/payload")
```
**CVE-2022-31163**
`CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H` …

Fixed @ CVE-2022-31163

---

docs/Gemfile.lock

Signed-off-by: mik-patient <112659896+mik-patient@users.noreply.github.com>
CommonMarker uses cmark-gfm for rendering [Github Flavored Markdown](https://github.github.com/gfm/). A polynomial time complexity issue in cmark-gfm's autolink extension may lead to unbounded resource exhaustion and subsequent denial of service.
https://github.com/gjtorikian/commonmarker/pull/190
[GHSA-cgh3-p57x-9q7q](https://github.com/github/cmark-gfm/security/advisories/GHSA-cgh3-p57x-9q7q)
https://en.wikipedia.org/wiki/Time_complexity

Fixed CWE-400 Uncontrolled Resource Consumption

---

.github/workflows/go-bindings.yml

The last successfull push to fabric-protos-go-apiv2 was before the update to the PUBLISH_GO_V2 secret so switching back to FABRIC_PROTOS_GO_APIV2_DEPLOY_KEY
Also moved the deploy key setup to a seperate step which should hopefully fix the apiv2 tagging

Revert to using FABRIC_PROTOS_GO_APIV2_DEPLOY_KEY

---

common/common.proto

Making field ORDERER_TRANSACTION in HeaderType deprecated, as it used only by the system channel.
Issue: https://github.com/hyperledger/fabric/issues/4206

system channel cleanup - make HeaderType_ORDERER_TRANSACTION deprecated

---

peer/lifecycle/lifecycle.proto

This patch extends lifecycle protos to checkcommitreadiness to provide discrepancy details.
- New feature
I have proposed an extension to lifecycle chaincode checkcommitreadiness to provide details of the discrepancies as shown in  https://github.com/hyperledger/fabric/issues/4428.
As a sub-task stemming from issue #4428, this patch extends lifecycle protos to checkcommitreadiness to provide discrepancy details.
To maintain backward compatibility with the previous versions of checkcommitreadiness, I've opted to introduce a field named `mismatches`.
Once this patch is merged, I plan to enhance the command and submit it to the Fabric repository. A provisional implementation is provided below:
- https://github.com/satota2/fabric/commit/58db22d9c9d5d04f10001cb45329e2f440d0a5b3
- …

Extend lifecycle protos to checkcommitreadiness to provide discrepancy details

---

.github/workflows/node-bindings.yml

Pushed commits to the main branch published NPM packages tagged as `unstable`, and release tags on the main branch published NPM packaged tagged as `latest`. This conflicted with NPM packages published from the 0.2.x branch and meant that the target Fabric version for the NPM package currently tagged `latest` varied depending on which branch had a release created most recently. The `latest` tag should always correspond to the current Fabric LTS release since it is the default version installed if a specific version is not specified.
Closes #191

Tag NPM packages from main branch as either next or next-unstable

---

.github/workflows/node-bindings.yml
.gitignore

Pushed commits to the main branch published NPM packages tagged as `unstable`, and release tags on the main branch published NPM packaged tagged as `latest`. This conflicted with NPM packages published from the 0.2.x branch and meant that the target Fabric version for the NPM package currently tagged `latest` varied depending on which branch had a release created most recently. The `latest` tag should always correspond to the current Fabric LTS release since it is the default version installed if a specific version is not specified.
Also update .gitignore to exclude files that should not be checked in.
Contributes to #191

Tag NPM packages from 0.1.x branch as either v1-latest or v1-unstable

---

peer/lifecycle/lifecycle.proto

This patch extends lifecycle protos to query all approved chaincode definitions.
See https://github.com/hyperledger/fabric/issues/4564 for the detail.
- New feature
As a sub-task stemming from issue #4564, this patch extends lifecycle protos to query all approved chaincode definitions.
I have already done the provisional implementation and will submit them to the Fabric repository once this patch is merged.
The example of output when executing the enhanced queryapproved in the provisional implementation:
```
$ peer lifecycle chaincode queryapproved -C mychannel
Approved chaincode definition on channel 'mychannel':
name: basic2, sequence: 2, version: 1.0.1, init-required: false, package-id: basic2_1.0.1:dae4dca432d56265e87e6416b602b40e94e7f7cdc177031abda1c81d9ed4258a, endorsement plugin: …
```

Extend lifecycle protos to query all approved chaincode definitions

---

.github/workflows/ci-checks.yml
.github/workflows/go-bindings.yml

set-output is deprecated. This commit replaces it with the suggested change.

Replace deprecated set-output in Github Actions

---

peer/chaincode.proto
peer/chaincode_shim.proto

https://github.com/hyperledger/fabric/issues/5086

add write batch to state

---

peer/chaincode.proto
peer/chaincode_shim.proto

https://github.com/hyperledger/fabric/issues/5116

add support GetMultipleKeys
