- discovery/protocol.proto
- gossip/message.proto
Signed-off-by: Mark S. Lewis <mark_lewis@uk.ibm.com>
> FAB-16501: Add missing java_package entries

- common/collection.proto
Signed-off-by: Danny Cao <dcao@us.ibm.com>
> [FAB-16963] Remove CollectionCriteria proto

- common/collection.proto
- common/policies.proto
- peer/policy.proto
* Deprecate peer.ApplicationPolicy in favor of common.ApplicationPolicy
for preventing future import cycles
Signed-off-by: Danny Cao <dcao@us.ibm.com>
> [FAB-15066] Add endorsement_policy to StaticCollectionConfig

- common/policies.proto
- peer/collection.proto
- peer/policy.proto
* Deprecate old collection.proto messages
* Deprecate common.ApplicationPolicy
Signed-off-by: Danny Cao <dcao@us.ibm.com>
> [FAB-17120] Move collection.proto from common to peer

- gossip/message.proto
- peer/lifecycle/lifecycle.proto
- transientstore/transientstore.proto
Signed-off-by: Danny Cao <dcao@us.ibm.com>
> [FAB-17120] Update common/collection.proto references in other protos

- common/configtx.proto
We were having a conversation about protos and it came out that these are dead and should be removed.  This commit removes them.
> Remove dead messages

- peer/collection.proto
- peer/configuration.proto
* Also reorganize ordering while it's still not used
/cc @jyellick @denyeart
> [FAB-17303] Add more fields to PrivateDataImplicitCollection

- peer/collection.proto
- peer/configuration.proto
This reverts commit ac9156dfc571a12aceb7cdd8f003d850761e779c.
Revert "[FAB-17303] Support new organization configuration field (#21)"
This reverts commit 6d951158d8a88926759917af8b8bcfdbbba68673.
> Revert "[FAB-17303] Add more fields to PrivateDataImplicitCollection"

- peer/peer.proto
> Branch test

- .gitignore
- ci/Dockerfile
Signed-off-by: K mehant <411843@student.nitandhra.ac.in>
> Better use of WORKDIR in dockerfile

- peer/snapshot.proto
> [FAB-18105] Add grpc service and protobuf msgs for snapshot mgmt CLI commands

- common/ledger.proto
> Add new proto msg BootstrappingSnapshotInfo to BlockchainInfo

- peer/query.proto
> [FAB-18324] Add JoinBySnapshotStatus proto msg as a query response

- gateway/gateway.proto
The gateway service should be in the gateway package.
> Fix the package declaration gateway service

- gateway/gateway.proto
Add offline signing support to latest gateway protos
> Gateway updates

- gateway/gateway.proto
Include transaction result in PreparedTransaction
> Gateway update

- .github/settings.yml
- ci/azure-pipelines.yml
- ci/build.sh
Update "master" branch references to "main".
Signed-off-by: David Enyeart <enyeart@us.ibm.com>
> Update "master" branch references to "main"

- gateway/gateway.proto
Enables replay of chaincode events.
> Add start_position to gateway.ChaincodeEventsRequest

- ci/azure-pipelines.yml
Signed-off-by: David Enyeart <enyeart@us.ibm.com>
> Update CI ubuntu to 20.04

- peer/chaincode_shim.proto
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
> Add in the purge-private-data API

- .gitignore
- Makefile
- bindings/java/.gitignore
- bindings/java/pom.xml
- buf.gen.yaml
Adds a Java template project and associate code generation
> Add binding generation for Java

- .github/workflows/makefile.yml
Use GitHub actions for new CI, starting with a make action on push and pull requests
> Initial GitHub action

- .github/workflows/publish-node.yml
Make module public and tag with latest
> Update node publish

- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
- Makefile
- bindings/java/pom.xml
> Publish Java bindings

- .github/workflows/java-bindings.yml
Fix missing working directory in publish step
> Fix Mavan publish

- .github/workflows/gh-pages.yml
Previous attempt failed with…
fatal: could not read Password for 'https://***@github.com': No such device or address
> Publish generated API documentation

- CONTRIBUTING.md
- README.md
- RELEASING.md
- buf.yaml
Update linting rules to exclude PACKAGE_VERSION_SUFFIX and add comment
that new files should not be excluded from remaining rules
Add specific hash to run breaking change detection against until there is a better release process
> Update repository documentation and lint rules

- .github/workflows/java-bindings.yml
- bindings/java/pom.xml
Update build to publish Java bindings to the central repository for
tagged releases
Requires the following repository secrets:
- OSSRH_USERNAME
- OSSRH_TOKEN
- OSSRH_GPG_SECRET_KEY
- OSSRH_GPG_SECRET_KEY_PASSWORD
> Release Java bindings to Maven Central Repository

- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
Release builds will be triggered by creating a new tag, e.g. v0.1.0
> Update builds to run for version tags

- .github/workflows/gh-pages.yml
Switch from placeholder email.
Signed-off-by: Ry Jones <ry@linux.com>
> Use bot email

- .github/scripts/installDeployKey.sh
- .github/workflows/go-bindings.yml
Previous publish failed with permission denied
> Use deploy key to publish Go apiv2 bindings

- .github/workflows/ci-checks.yml
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
> Bump version to 0.1.1

- .github/workflows/ci-checks.yml
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
> Bump version to 0.1.4

- common/configuration.proto
> Add consenter mapping to config proto

- Makefile
- common/configuration.proto
> Change Consenter id to uin32

- Makefile
Issue: https://github.com/hyperledger/fabric/issues/3513
Epic: https://github.com/hyperledger/fabric/issues/3511
Signed-off-by: Yoav Tock <tock@il.ibm.com>
> Orderer v3: restore makefile

- orderer/ab.proto
> Add SeekContentType to orderer proto

- .github/pull_request_template.md
- RELEASING.md
> Document approach to versioning and breaking changes

- .github/workflows/go-bindings.yml
Moved FABRIC_PROTOS_GO_APIV2_DEPLOY_KEY env to the correct step
> Fix Go bindings workflows

- buf.yaml
- orderer/smartbft/configuration.proto
added configuration options for smartbft consenter
Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>
> smartbft configuration protobuf message

- buf.yaml
- orderer/smartbft/configuration.proto
Signed-off-by: Yacov Manevich <yacovm@il.ibm.com>
> Appease linter for SmartBFT configuration protobuf file

- .github/scripts/installDeployKey.sh
> Ensure build fails if deploy key is not installed

- .github/scripts/installDeployKey.sh
Remove illegal option -o pipefail
> Fix installDeployKey.sh

- .github/workflows/ci-checks.yml
- RELEASING.md
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
Also updates RELEASING.md with latest instructions
> Prepare 0.3.0 release

- .github/workflows/ci-checks.yml
- RELEASING.md
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
Also add missing maven link to RELEASING.md
> Bump version to 0.3.1

- RELEASING.md
- docs/index.md
> Update doc to reflect new branching strategy

- .github/workflows/ci-checks.yml
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
> Bump version to 0.2.1

- .github/workflows/ci-checks.yml
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
> Bump version to 0.1.7

- bindings/java/pom.xml
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
> Update Java proto library

- bindings/java/pom.xml
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
> Update Java Protobuf library to remove dependency issues

- .github/workflows/ci-checks.yml
- .github/workflows/gh-pages.yml
- .github/workflows/go-bindings.yml
- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
> Bump Go to 1.19

- .github/workflows/ci-checks.yml
- .github/workflows/gh-pages.yml
- .github/workflows/go-bindings.yml
- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
> Bump Go to 1.20

- .github/workflows/ci-checks.yml
- .github/workflows/gh-pages.yml
- .github/workflows/go-bindings.yml
- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
> Bump Go to 1.20.2 (branch 0.2.x)

- RELEASING.md
> Update release readme

- .github/workflows/go-bindings.yml
Update CI commit message to be a single line subject.
> Update CI commit message

- .github/workflows/ci-checks.yml
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
> Update version to v0.3.2

- .github/workflows/ci-checks.yml
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
> Release v0.3.3 commit

- .github/workflows/ci-checks.yml
- .github/workflows/gh-pages.yml
- .github/workflows/go-bindings.yml
- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
- .github/workflows/vulnerability-scan.yml
> Bump Go to 1.21.6

- .github/workflows/ci-checks.yml
- .github/workflows/gh-pages.yml
- .github/workflows/go-bindings.yml
- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
- .github/workflows/vulnerability-scan.yml
- actions/setup-go@v5
- actions/checkout@v4
- actions/cache@v4
- actions/setup-java@v4
> Update Github Actions to use Node 20

- .github/workflows/ci-checks.yml
- .github/workflows/gh-pages.yml
- .github/workflows/go-bindings.yml
- .github/workflows/java-bindings.yml
- .github/workflows/node-bindings.yml
- actions/setup-go@v5
- actions/checkout@v4
- actions/cache@v4
- actions/setup-java@v4
- actions/setup-node@v4
> Update Github Actions to use Node 20 (branch 0.2.x)

- .github/workflows/ci-checks.yml
- bindings/java/pom.xml
- bindings/node/package-lock.json
- bindings/node/package.json
> Release v0.3.5 commit
